INSERT INTO category(name)
VALUES ('Action and adventure'),
       ('Anthology'),
       ('Classic'),
       ('Comic and Graphic novel'),
       ('Drama'),
       ('Fable'),
       ('Fairy Tale'),
       ('Fan-Fiction'),
       ('Fantasy'),
       ('Historical Fiction'),
       ('Horror'),
       ('Humor'),
       ('Legend'),
       ('Magical Realism'),
       ('Mystery'),
       ('Mythology'),
       ('Realistic Fiction'),
       ('Romance'),
       ('Satire'),
       ('Science Fiction'),
       ('Short Story'),
       ('Suspense/Thriller'),
       ('Biography/Autobiography');